runtime: python39
service: iris3
automatic_scaling:
  max_instances: 3
  max_concurrent_requests: 3
instance_class: F2
inbound_services:
  - warmup
app_engine_apis: true
env_variables:
  GAE_USE_SOCKETS_HTTPLIB: false
# can add this to env_variables for more accurate memray output
#  PYTHONMALLOC: malloc




