runtime: python39
service: iris3
automatic_scaling:
  max_instances: 10
  # max_concurrent_requests: 20
instance_class: F2
inbound_services:
  - warmup
env_variables:
  GAE_USE_SOCKETS_HTTPLIB: False
app_engine_apis: true


