# If you see this comment, you are using a config file that was temporarily generated for a test.
#
# In integration_test.sh, config.yaml.test.template is used to make a temporary config.yaml, then config.yaml is reverted at the end.
#
# Generate random token per-test-run as an additional isolation measure
pubsub_verification_token: a129f6ac270cc1ae3b4398b4422e5798
iris_prefix: iris9i3vws
from_project: True
label_all_on_cron: False
projects:
  - joshua-playground2
  - joshua-playground-host-vpc
