# config.yaml.original is a clean version that you can refer to after you have edited config.yaml.
# You can even set up a git pre-commit hook to replace config.yaml with this clean version to avoid committing an edited version.

# Keys:

# projects: Only resources in these projects will get labeled.
# But if the value is empty, *all* projects in the organization are included.
projects: [ ]

# plugins: Only these plugins are enabled.
# For example, add some of these to the list:
#     bigquery, buckets, disks,  cloudsql, instances, snapshots, subscriptions, topics
# But if the value is empty, *all* plugins are enabled
plugins: [ ]

# iris_prefix plus underscore is prefixed to the key of each label that is added.
#    If empty string is used (the default), then there is no prefix
iris_prefix: iris

# specific_prefixes gives a prefix per resource type, overriding iris_prefix.
# The default is that there is no override.
# Empty vs empty-string:
#  - An empty value, as in the Buckets example below, is treated as "None"
#   and will not replace the general iris_prefix.
#  - Empty string, as in the Bigquery example below, overrides
#   the iris_prefix with empty-string, so that you get labels with no prefix.
# The comment below gives an example.
specific_prefixes: { }

# Example:
# specific_prefixes:
#  Buckets:
#  Bigquery: ""
#  Cloudsql: sql
#  Disks: gcedisk
#  Instances: gce
#  Snapshots:
#  Subscriptions:
#  Topics:

# If from_project is True, then for each resource we are labeling, copy the labels from its project onto it.
# The default is False.
from_project: True

# If label_all_on_cron is True, then all resource types will be labeled on every cron (Cloud Scheduler) cycle.
#   This is also good for labeling existing resources on first running Iris3.
# If label_all_on_cron is False (the default), then to save money,
#  only resources of certain types get labeled on cron: those whose plugins either
#    - return True on relabel_on_cron() (like Disks)
#    - or return False in is_labeled_on_creation() (like Cloud SQL)
label_all_on_cron: False

# Optionally change this before first deployment for added security in
# communication between PubSub and the Iris App on App Engine.
# You could even re-generate a new token per deployment.
# Note that this approach is not very secure, though it  was once recommended by Google.
# However, so long as our GCP project is secure, this token protects against
# unwanted repetitions of the labeling command.
pubsub_verification_token: 0b0a30cde7e3489f0a9cd74bb51c514d
