# If you see this comment, you are using a config file that was temporarily generated for a test.
#
# In integration_test.sh, config.yaml.test.template is used to make a temporary config.yaml, then config.yaml is reverted at the end.
#
iris_prefix: iris6coaz8
from_project: True
label_all_on_cron: False
projects:
  - joshua-playground2
  - joshua-playground-host-vpc
