# If you see this comment, you are using a config file that was temporarily generated for a test.
#
# When running integration_test.sh, this template is used to make a temporary config.yaml, then config.yaml is reverted at the end.
#
projects:
  - joshua-playground2
  - joshua-playground-host-vpc
plugins: []
iris_prefix: irismqmrio
specific_prefixes:
  Buckets: gcsirismqmrio
from_project: True
label_all_on_cron: False
# We generate a random token per-test-run as an additional isolation measure
pubsub_verification_token: 522766a41687df9bff7f6011d2a3ba20
