# config.yaml.original is a "clean" version that you can refer to after you have edited config.yaml.
# You can even set up a git pre-commit hook to replace config.yaml with this clean version to avoid commiting an edited version.
#
#
# Keys:

# iris_prefix is prefixed to the key of each label that is added.
iris_prefix: iris

# If from_project is True, then for each resource we are labeling, copy the labels from its project onto it.
from_project: True

# If label_all_on_cron is True, then all resource types will be labeled on every cron (Clouid Scheduler) cycle.
# If label_all_on_cron is Fals,e then only plugins with  relabel_on_cron True or is_labeled_on_creation False
# get labeled on cron. Labeling *all* resources is very expensive, so default is False
label_all_on_cron: False

#  Only these projects are included. But if empty, *all* projects in the organization are included.
projects: {}